# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y-_cthaLm5Uaagqdx1u74_MzQTUoK7hR
"""

from google.colab import files
files.upload()

!pip install kaggle
!mkdir -p ~/.kaggle
!mv kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

!kaggle datasets download -d confirm/google-landmark-dataset-v2-micro

!unzip -q google-landmark-dataset-v2-micro.zip -d /content/landmark_data

!ls /content/landmark_data/gldv2_micro

import pandas as pd

df = pd.read_csv("/content/landmark_data/gldv2_micro/train.csv")
print(df.shape)
print(df.head())

import pandas as pd
import matplotlib.pyplot as plt
from PIL import Image
import os

# Пути
csv_path = "/content/landmark_data/gldv2_micro/train.csv"
img_dir = "/content/landmark_data/gldv2_micro/images"

# Загружаем таблицу
df = pd.read_csv(csv_path)
print(df.shape)
print(df.head())

# Берём первые 5 примеров
sample_df = df.sample(5, random_state=42)

# Визуализация
plt.figure(figsize=(15, 6))
for i, row in enumerate(sample_df.itertuples(), 1):
    img_path = os.path.join(img_dir, row.filename)
    image = Image.open(img_path)
    plt.subplot(1, 5, i)
    plt.imshow(image)
    plt.title(f"Landmark ID: {row.landmark_id}")
    plt.axis("off")

plt.show()